{"metadata":{"modules":[{"name":"ContextSDK"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"log","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EventOutcome","kind":"typeIdentifier","preciseIdentifier":"c:@M@ContextSDK@E@EventOutcome"},{"text":")","kind":"text"}],"title":"log(_:)","roleHeading":"Instance Method","role":"symbol","externalID":"s:10ContextSDK0A0C3logyyAA12EventOutcomeOF"},"abstract":[{"type":"text","text":"Use this method to log an outcome and send the context event to the backend."}],"variants":[{"paths":["\/documentation\/contextsdk\/context\/log(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"log"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"outcome","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ContextSDK@E@EventOutcome","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome","text":"EventOutcome"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The outcome being logged."}]}],"name":"outcome"}],"kind":"parameters"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context\/log(_:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Context":{"navigatorTitle":[{"text":"Context","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context","title":"Context","type":"topic","abstract":[{"type":"text","text":"Represents a full context event in a moment in time. Use "},{"type":"codeVoice","code":".log"},{"type":"text","text":" to create a "},{"type":"codeVoice","code":"Log"},{"text":" object, which allows you to send the context event to the backend.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Context"}],"kind":"symbol","url":"\/documentation\/contextsdk\/context"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Context/log(_:)":{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context\/log(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"log"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ContextSDK@E@EventOutcome","text":"EventOutcome","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"log(_:)","kind":"symbol","abstract":[{"text":"Use this method to log an outcome and send the context event to the backend.","type":"text"}],"role":"symbol","url":"\/documentation\/contextsdk\/context\/log(_:)"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome":{"role":"symbol","abstract":[],"title":"EventOutcome","navigatorTitle":[{"text":"EventOutcome","kind":"identifier"}],"url":"\/documentation\/contextsdk\/eventoutcome","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"EventOutcome","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK":{"abstract":[],"type":"topic","title":"ContextSDK","url":"\/documentation\/contextsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"EventOutcome","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/fragments","value":[{"text":"EventOutcome","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"EventOutcome"}],"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/navigatorTitle","op":"replace"}]}]}