{
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/BaseLog"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "occ",
    "url" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/BaseLog\/init"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@M@ContextSDK@objc(cs)BaseLog(im)init",
    "fragments" : [
      {
        "kind" : "text",
        "text" : "- "
      },
      {
        "kind" : "identifier",
        "text" : "init"
      }
    ],
    "modules" : [
      {
        "name" : "ContextSDK"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "init"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Instance Method",
    "symbolKind" : "method",
    "title" : "init"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "occ"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "text",
              "text" : "- ("
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:*Qo",
              "text" : "id"
            },
            {
              "kind" : "text",
              "text" : ") "
            },
            {
              "kind" : "identifier",
              "text" : "init"
            },
            {
              "kind" : "text",
              "text" : ";"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/contextsdk\/baselog\/init"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "ContextSDK",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/BaseLog": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "BaseLog"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/BaseLog",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "BaseLog"
    }
  ],
  "role" : "symbol",
  "title" : "BaseLog",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/baselog"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/BaseLog/init": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "text",
      "text" : "- "
    },
    {
      "kind" : "identifier",
      "text" : "init"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/BaseLog\/init",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "init"
    }
  ],
  "role" : "symbol",
  "title" : "init",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/baselog\/init"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1BaseLog\/title",
        "value" : "BaseLog"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1BaseLog\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "BaseLog"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1BaseLog\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "BaseLog"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}