{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applicationDidFinishLaunchingWithOptions"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"launchOptions","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey","text":"LaunchOptionsKey"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"text":"licenseKey","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Configuration","preciseIdentifier":"c:@M@ContextSDK@objc(cs)Configuration","kind":"typeIdentifier","text":"Configuration"},{"text":" = Configuration()) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/contextsdk\/contextmanager\/applicationdidfinishlaunchingwithoptions(_:licensekey:configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/contextsdk\/contextmanager\/applicationdidfinishlaunchingwithoptions(_:licensekey:configuration:)"]}],"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"applicationDidFinishLaunchingWithOptions","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"LaunchOptionsKey","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"licenseKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ContextSDK@objc(cs)Configuration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"applicationDidFinishLaunchingWithOptions:licenseKey:configuration:","kind":"identifier"}],"externalID":"c:@M@ContextSDK@objc(cs)ContextManager(cm)applicationDidFinishLaunchingWithOptions:licenseKey:configuration:","roleHeading":"Type Method","modules":[{"name":"ContextSDK"}],"role":"symbol","title":"applicationDidFinishLaunchingWithOptions(_:licenseKey:configuration:)","symbolKind":"method"},"identifier":{"url":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/applicationDidFinishLaunchingWithOptions(_:licenseKey:configuration:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/applicationDidFinishLaunchingWithOptions(_:licenseKey:configuration:)":{"kind":"symbol","url":"\/documentation\/contextsdk\/contextmanager\/applicationdidfinishlaunchingwithoptions(_:licensekey:configuration:)","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/applicationDidFinishLaunchingWithOptions(_:licenseKey:configuration:)","title":"applicationDidFinishLaunchingWithOptions(_:licenseKey:configuration:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"applicationDidFinishLaunchingWithOptions","kind":"identifier"},{"kind":"text","text":"(["},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey","kind":"typeIdentifier","text":"LaunchOptionsKey"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"licenseKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ContextSDK@objc(cs)Configuration","text":"Configuration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"applicationDidFinishLaunchingWithOptions:licenseKey:configuration:","kind":"identifier"}]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Configuration":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Configuration","url":"\/documentation\/contextsdk\/configuration","title":"Configuration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager":{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager","abstract":[],"role":"symbol","url":"\/documentation\/contextsdk\/contextmanager","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContextManager"}],"title":"ContextManager","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContextManager"}]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK":{"abstract":[],"type":"topic","title":"ContextSDK","url":"\/documentation\/contextsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"applicationDidFinishLaunchingWithOptions:licenseKey:configuration:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"applicationDidFinishLaunchingWithOptions:licenseKey:configuration:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"applicationDidFinishLaunchingWithOptions:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"launchOptions","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"licenseKey:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"licenseKey"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ContextSDK@objc(cs)Configuration","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Configuration","kind":"typeIdentifier","text":"Configuration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"configuration"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1applicationDidFinishLaunchingWithOptions(_:licenseKey:configuration:)\/title","op":"replace","value":"applicationDidFinishLaunchingWithOptions:licenseKey:configuration:"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1applicationDidFinishLaunchingWithOptions(_:licenseKey:configuration:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"applicationDidFinishLaunchingWithOptions:licenseKey:configuration:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Configuration\/title","value":"Configuration","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Configuration\/fragments","value":[{"kind":"identifier","text":"Configuration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Configuration\/navigatorTitle","value":[{"text":"Configuration","kind":"identifier"}]},{"value":"ContextManager","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager\/fragments","value":[{"text":"ContextManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager\/navigatorTitle","value":[{"kind":"identifier","text":"ContextManager"}]}]}]}