{
  "abstract" : [
    {
      "text" : "Initializes ContextSDK. Call this once in your ",
      "type" : "text"
    },
    {
      "code" : "UIApplicationDelegate",
      "type" : "codeVoice"
    },
    {
      "text" : "’s ",
      "type" : "text"
    },
    {
      "code" : "application:didFinishLaunchingWithOptions:",
      "type" : "codeVoice"
    },
    {
      "text" : " method.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/applicationDidFinishLaunchingWithOptions(_:licenseKey:)"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@M@ContextSDK@objc(cs)ContextManager(cm)applicationDidFinishLaunchingWithOptions:licenseKey:",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "class"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "keyword",
        "text" : "func"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "applicationDidFinishLaunchingWithOptions"
      },
      {
        "kind" : "text",
        "text" : "(["
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:objc(cs)UIApplication",
        "text" : "UIApplication"
      },
      {
        "kind" : "text",
        "text" : "."
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:@T@UIApplicationLaunchOptionsKey",
        "text" : "LaunchOptionsKey"
      },
      {
        "kind" : "text",
        "text" : " : "
      },
      {
        "kind" : "keyword",
        "text" : "Any"
      },
      {
        "kind" : "text",
        "text" : "]?, "
      },
      {
        "kind" : "externalParam",
        "text" : "licenseKey"
      },
      {
        "kind" : "text",
        "text" : ": "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:SS",
        "text" : "String"
      },
      {
        "kind" : "text",
        "text" : ") -> "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:Sb",
        "text" : "Bool"
      }
    ],
    "modules" : [
      {
        "name" : "ContextSDK"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "applicationDidFinishLaunchingWithOptions:licenseKey:"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Type Method",
    "symbolKind" : "method",
    "title" : "applicationDidFinishLaunchingWithOptions(_:licenseKey:)"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "attribute",
              "text" : "@discardableResult"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "attribute",
              "text" : "@objc"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "keyword",
              "text" : "class"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "keyword",
              "text" : "func"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "applicationDidFinishLaunchingWithOptions"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "launchOptions"
            },
            {
              "kind" : "text",
              "text" : ": ["
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:objc(cs)UIApplication",
              "text" : "UIApplication"
            },
            {
              "kind" : "text",
              "text" : "."
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:@T@UIApplicationLaunchOptionsKey",
              "text" : "LaunchOptionsKey"
            },
            {
              "kind" : "text",
              "text" : " : "
            },
            {
              "kind" : "keyword",
              "text" : "Any"
            },
            {
              "kind" : "text",
              "text" : "]?, "
            },
            {
              "kind" : "externalParam",
              "text" : "licenseKey"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:SS",
              "text" : "String"
            },
            {
              "kind" : "text",
              "text" : ") -> "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:Sb",
              "text" : "Bool"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "kind" : "parameters",
      "parameters" : [
        {
          "content" : [
            {
              "inlineContent" : [
                {
                  "text" : "The launchOptions as passed by ",
                  "type" : "text"
                },
                {
                  "code" : "UIApplicationDelegate",
                  "type" : "codeVoice"
                },
                {
                  "text" : "’s ",
                  "type" : "text"
                },
                {
                  "code" : "application:didFinishLaunchingWithOptions:",
                  "type" : "codeVoice"
                },
                {
                  "text" : " method.",
                  "type" : "text"
                }
              ],
              "type" : "paragraph"
            }
          ],
          "name" : "launchOptions"
        },
        {
          "content" : [
            {
              "inlineContent" : [
                {
                  "text" : "Your personal ContextSDK license key specific to the current bundle identifier.",
                  "type" : "text"
                }
              ],
              "type" : "paragraph"
            }
          ],
          "name" : "licenseKey"
        }
      ]
    },
    {
      "content" : [
        {
          "anchor" : "return-value",
          "level" : 2,
          "text" : "Return Value",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "Whether ContextSDK was initialized or not. It will fail if the license key is invalid, for instance.",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/contextsdk\/contextmanager\/applicationdidfinishlaunchingwithoptions(_:licensekey:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/contextsdk\/contextmanager\/applicationdidfinishlaunchingwithoptions(_:licensekey:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "ContextSDK",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager": {
  "abstract" : [
    {
      "text" : "The main interface to be used to interact with ContextSDK.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ContextManager"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ContextManager"
    }
  ],
  "role" : "symbol",
  "title" : "ContextManager",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextmanager"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/applicationDidFinishLaunchingWithOptions(_:licenseKey:)": {
  "abstract" : [
    {
      "text" : "Initializes ContextSDK. Call this once in your ",
      "type" : "text"
    },
    {
      "code" : "UIApplicationDelegate",
      "type" : "codeVoice"
    },
    {
      "text" : "’s ",
      "type" : "text"
    },
    {
      "code" : "application:didFinishLaunchingWithOptions:",
      "type" : "codeVoice"
    },
    {
      "text" : " method.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "applicationDidFinishLaunchingWithOptions"
    },
    {
      "kind" : "text",
      "text" : "(["
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)UIApplication",
      "text" : "UIApplication"
    },
    {
      "kind" : "text",
      "text" : "."
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:@T@UIApplicationLaunchOptionsKey",
      "text" : "LaunchOptionsKey"
    },
    {
      "kind" : "text",
      "text" : " : "
    },
    {
      "kind" : "keyword",
      "text" : "Any"
    },
    {
      "kind" : "text",
      "text" : "]?, "
    },
    {
      "kind" : "externalParam",
      "text" : "licenseKey"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    },
    {
      "kind" : "text",
      "text" : ") -> "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Sb",
      "text" : "Bool"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/applicationDidFinishLaunchingWithOptions(_:licenseKey:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "applicationDidFinishLaunchingWithOptions:licenseKey:"
    }
  ],
  "role" : "symbol",
  "title" : "applicationDidFinishLaunchingWithOptions(_:licenseKey:)",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextmanager\/applicationdidfinishlaunchingwithoptions(_:licensekey:)"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Type Method"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "applicationDidFinishLaunchingWithOptions:licenseKey:"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "method"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "+ "
          },
          {
            "kind" : "identifier",
            "text" : "applicationDidFinishLaunchingWithOptions:licenseKey:"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "text",
                  "text" : "+ ("
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@T@BOOL",
                  "text" : "BOOL"
                },
                {
                  "kind" : "text",
                  "text" : ") "
                },
                {
                  "kind" : "identifier",
                  "text" : "applicationDidFinishLaunchingWithOptions:"
                },
                {
                  "kind" : "text",
                  "text" : "("
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:Q$objc(cs)NSDictionary",
                  "text" : "NSDictionary<NSString *,id>"
                },
                {
                  "kind" : "text",
                  "text" : " *) "
                },
                {
                  "kind" : "internalParam",
                  "text" : "launchOptions"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "identifier",
                  "text" : "licenseKey:"
                },
                {
                  "kind" : "text",
                  "text" : "("
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:objc(cs)NSString",
                  "text" : "NSString"
                },
                {
                  "kind" : "text",
                  "text" : " *) "
                },
                {
                  "kind" : "internalParam",
                  "text" : "licenseKey"
                },
                {
                  "kind" : "text",
                  "text" : ";"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/1",
        "value" : {
          "kind" : "parameters",
          "parameters" : [
            {
              "content" : [
                {
                  "inlineContent" : [
                    {
                      "text" : "The launchOptions as passed by ",
                      "type" : "text"
                    },
                    {
                      "code" : "UIApplicationDelegate",
                      "type" : "codeVoice"
                    },
                    {
                      "text" : "’s ",
                      "type" : "text"
                    },
                    {
                      "code" : "application:didFinishLaunchingWithOptions:",
                      "type" : "codeVoice"
                    },
                    {
                      "text" : " method.",
                      "type" : "text"
                    }
                  ],
                  "type" : "paragraph"
                }
              ],
              "name" : "launchOptions"
            },
            {
              "content" : [
                {
                  "inlineContent" : [
                    {
                      "text" : "Your personal ContextSDK license key specific to the current bundle identifier.",
                      "type" : "text"
                    }
                  ],
                  "type" : "paragraph"
                }
              ],
              "name" : "licenseKey"
            }
          ]
        }
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/2",
        "value" : {
          "content" : [
            {
              "anchor" : "return-value",
              "level" : 2,
              "text" : "Return Value",
              "type" : "heading"
            },
            {
              "inlineContent" : [
                {
                  "text" : "Whether ContextSDK was initialized or not. It will fail if the license key is invalid, for instance.",
                  "type" : "text"
                }
              ],
              "type" : "paragraph"
            }
          ],
          "kind" : "content"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager\/title",
        "value" : "ContextManager"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "ContextManager"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "ContextManager"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1applicationDidFinishLaunchingWithOptions(_:licenseKey:)\/title",
        "value" : "applicationDidFinishLaunchingWithOptions:licenseKey:"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1applicationDidFinishLaunchingWithOptions(_:licenseKey:)\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "+ "
          },
          {
            "kind" : "identifier",
            "text" : "applicationDidFinishLaunchingWithOptions:licenseKey:"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}