{"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please contact us support@contextsdk.com in case you want to use ContextSDK with your own backend"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/contextsdk\/contextmanager\/setlogsender(closure:)"]}],"metadata":{"role":"symbol","modules":[{"name":"ContextSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLogSender"},{"kind":"text","text":"("},{"text":"closure","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ContextSDK@objc(cs)Log","text":"Log","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":"))"}],"externalID":"s:10ContextSDK0A7ManagerC12setLogSender7closureyyAA0E0Cc_tFZ","platforms":[],"roleHeading":"Type Method","title":"setLogSender(closure:)","symbolKind":"method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLogSender"},{"kind":"text","text":"("},{"text":"closure","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log","text":"Log","kind":"typeIdentifier","preciseIdentifier":"c:@M@ContextSDK@objc(cs)Log"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":"))","kind":"text"}],"languages":["swift"]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"This function takes in a closure that will be called with a ","type":"text"},{"type":"codeVoice","code":"Log"},{"text":" object everytime you use ","type":"text"},{"code":"Context.log(outcome:)","type":"codeVoice"},{"type":"text","text":".  Inside this closure you can send the "},{"code":"Log","type":"codeVoice"},{"type":"text","text":" to your own backend or use the "},{"type":"codeVoice","code":"Log.send()"},{"text":" method to send it to the ContextSDK backend. Calling this will replace any previously set log senders.","type":"text"}]}]}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setLogSender(closure:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log":{"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Log"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Log","kind":"identifier"}],"kind":"symbol","title":"Log","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log","url":"\/documentation\/contextsdk\/log"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","role":"collection","type":"topic","url":"\/documentation\/contextsdk","kind":"symbol","title":"ContextSDK"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ContextManager","kind":"identifier"}],"navigatorTitle":[{"text":"ContextManager","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/contextsdk\/contextmanager","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager","title":"ContextManager"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/setLogSender(closure:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setLogSender","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"closure"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ContextSDK@objc(cs)Log","text":"Log","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":"))","kind":"text"}],"role":"symbol","deprecated":true,"kind":"symbol","title":"setLogSender(closure:)","type":"topic","url":"\/documentation\/contextsdk\/contextmanager\/setlogsender(closure:)","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setLogSender(closure:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Log","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/fragments","value":[{"kind":"identifier","text":"Log"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/navigatorTitle","op":"replace","value":[{"text":"Log","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager\/title","value":"ContextManager","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager\/fragments","value":[{"text":"ContextManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ContextManager"}]}]}]}