{"abstract":[{"type":"text","text":"Optional outcome: Use this as a negative signal of a user not interacting with e.g. a banner. Depending on your app, we may recommend to log this when the app is put into the background, and hasn’t interacted with a banner in any way. This can be done using the "},{"type":"codeVoice","code":"logIfNotLoggedYet"},{"type":"text","text":" method"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/contextsdk\/eventoutcome\/negativedismissed"]},{"paths":["\/documentation\/contextsdk\/eventoutcome\/negativedismissed"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"EventOutcome.negativeDismissed","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"EventOutcomeNegativeDismissed"}],"modules":[{"name":"ContextSDK"}],"role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"negativeDismissed"}],"externalID":"c:@M@ContextSDK@E@EventOutcome@EventOutcomeNegativeDismissed"},"identifier":{"url":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negativeDismissed","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"negativeDismissed"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome"]]},"references":{"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome","type":"topic","role":"symbol","title":"EventOutcome","navigatorTitle":[{"text":"EventOutcome","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventOutcome"}],"url":"\/documentation\/contextsdk\/eventoutcome","abstract":[]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/negativeDismissed":{"navigatorTitle":[{"kind":"identifier","text":"EventOutcomeNegativeDismissed"}],"kind":"symbol","title":"EventOutcome.negativeDismissed","abstract":[{"text":"Optional outcome: Use this as a negative signal of a user not interacting with e.g. a banner. Depending on your app, we may recommend to log this when the app is put into the background, and hasn’t interacted with a banner in any way. This can be done using the ","type":"text"},{"code":"logIfNotLoggedYet","type":"codeVoice"},{"type":"text","text":" method"}],"role":"symbol","type":"topic","url":"\/documentation\/contextsdk\/eventoutcome\/negativedismissed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"negativeDismissed","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negativeDismissed"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","role":"collection","abstract":[],"title":"ContextSDK","url":"\/documentation\/contextsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"EventOutcomeNegativeDismissed","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"EventOutcomeNegativeDismissed"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"EventOutcomeNegativeDismissed","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"EventOutcome","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/title"},{"value":[{"kind":"identifier","text":"EventOutcome"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/fragments"},{"op":"replace","value":[{"text":"EventOutcome","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1negativeDismissed\/title","value":"EventOutcomeNegativeDismissed","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1negativeDismissed\/fragments","op":"replace","value":[{"kind":"identifier","text":"EventOutcomeNegativeDismissed"}]}]}]}