{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome"]]},"metadata":{"symbolKind":"case","title":"EventOutcome.negative","modules":[{"name":"ContextSDK"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"negative"}],"navigatorTitle":[{"text":"EventOutcomeNegative","kind":"identifier"}],"externalID":"c:@M@ContextSDK@E@EventOutcome@EventOutcomeNegative","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"negative"}]}]}],"abstract":[{"text":"Log this when ContextSDK has recommended to skip showing an upsell prompt (","type":"text"},{"type":"codeVoice","code":".shouldUpsell"},{"text":" is false). Logging this explicitly is not required if you use ","type":"text"},{"code":"ContextManager.optimize(…)","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"ContextManager.calibrate(…)"},{"type":"text","text":" as it will be handled by ContextSDK automatically."}],"variants":[{"paths":["\/documentation\/contextsdk\/eventoutcome\/negative"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/contextsdk\/eventoutcome\/negative"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negative","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/negative":{"abstract":[{"type":"text","text":"Log this when ContextSDK has recommended to skip showing an upsell prompt ("},{"code":".shouldUpsell","type":"codeVoice"},{"type":"text","text":" is false). Logging this explicitly is not required if you use "},{"type":"codeVoice","code":"ContextManager.optimize(…)"},{"type":"text","text":" or "},{"type":"codeVoice","code":"ContextManager.calibrate(…)"},{"text":" as it will be handled by ContextSDK automatically.","type":"text"}],"url":"\/documentation\/contextsdk\/eventoutcome\/negative","title":"EventOutcome.negative","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"negative","kind":"identifier"}],"navigatorTitle":[{"text":"EventOutcomeNegative","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negative","role":"symbol"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome":{"kind":"symbol","type":"topic","title":"EventOutcome","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome","url":"\/documentation\/contextsdk\/eventoutcome","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"EventOutcome","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"EventOutcome"}]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK":{"type":"topic","abstract":[],"title":"ContextSDK","role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","url":"\/documentation\/contextsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"EventOutcomeNegative","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"EventOutcomeNegative"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"EventOutcomeNegative"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1negative\/title","op":"replace","value":"EventOutcomeNegative"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1negative\/fragments","value":[{"text":"EventOutcomeNegative","kind":"identifier"}]},{"value":"EventOutcome","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/fragments","value":[{"kind":"identifier","text":"EventOutcome"}],"op":"replace"},{"op":"replace","value":[{"text":"EventOutcome","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/navigatorTitle"}]}]}