{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"negativeNotInteracted"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negativeNotInteracted","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"negativeNotInteracted"}],"role":"symbol","externalID":"c:@M@ContextSDK@E@EventOutcome@EventOutcomeNegativeNotInteracted","symbolKind":"case","modules":[{"name":"ContextSDK"}],"title":"EventOutcome.negativeNotInteracted","navigatorTitle":[{"kind":"identifier","text":"EventOutcomeNegativeNotInteracted"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/contextsdk\/eventoutcome\/negativenotinteracted"]},{"paths":["\/documentation\/contextsdk\/eventoutcome\/negativenotinteracted"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"A generic, negative signal. Use this for the basic ContextSDK integration, on a user e.g. declining or dismissing an upsell prompt"}],"references":{"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/negativeNotInteracted":{"title":"EventOutcome.negativeNotInteracted","abstract":[{"type":"text","text":"A generic, negative signal. Use this for the basic ContextSDK integration, on a user e.g. declining or dismissing an upsell prompt"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negativeNotInteracted","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"negativeNotInteracted","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/contextsdk\/eventoutcome\/negativenotinteracted","navigatorTitle":[{"kind":"identifier","text":"EventOutcomeNegativeNotInteracted"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK":{"type":"topic","abstract":[],"title":"ContextSDK","role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","url":"\/documentation\/contextsdk"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome":{"kind":"symbol","type":"topic","title":"EventOutcome","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome","url":"\/documentation\/contextsdk\/eventoutcome","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"EventOutcome","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"EventOutcome"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"EventOutcomeNegativeNotInteracted","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"EventOutcomeNegativeNotInteracted"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"EventOutcomeNegativeNotInteracted","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1negativeNotInteracted\/title","op":"replace","value":"EventOutcomeNegativeNotInteracted"},{"op":"replace","value":[{"kind":"identifier","text":"EventOutcomeNegativeNotInteracted"}],"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1negativeNotInteracted\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/title","value":"EventOutcome","op":"replace"},{"value":[{"text":"EventOutcome","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"EventOutcome"}]}]}]}