{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"positive","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"EventOutcomePositive"}],"symbolKind":"case","role":"symbol","title":"EventOutcome.positive","roleHeading":"Case","modules":[{"name":"ContextSDK"}],"externalID":"c:@M@ContextSDK@E@EventOutcome@EventOutcomePositive","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"positive","kind":"identifier"}]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positive","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/contextsdk\/eventoutcome\/positive"]},{"paths":["\/documentation\/contextsdk\/eventoutcome\/positive"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Optional outcome: The user has tapped on the banner, and started the purchase flow, or read more about the offer","type":"text"}],"references":{"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/positive":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"positive","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positive","type":"topic","abstract":[{"type":"text","text":"Optional outcome: The user has tapped on the banner, and started the purchase flow, or read more about the offer"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EventOutcomePositive"}],"title":"EventOutcome.positive","role":"symbol","url":"\/documentation\/contextsdk\/eventoutcome\/positive"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK":{"abstract":[],"type":"topic","title":"ContextSDK","url":"\/documentation\/contextsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome":{"role":"symbol","abstract":[],"title":"EventOutcome","navigatorTitle":[{"text":"EventOutcome","kind":"identifier"}],"url":"\/documentation\/contextsdk\/eventoutcome","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"EventOutcome","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"EventOutcomePositive","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"EventOutcomePositive","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"EventOutcomePositive","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"EventOutcomePositive","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1positive\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1positive\/fragments","op":"replace","value":[{"text":"EventOutcomePositive","kind":"identifier"}]},{"value":"EventOutcome","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/title"},{"value":[{"text":"EventOutcome","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/fragments","op":"replace"},{"value":[{"text":"EventOutcome","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}