{
  "abstract" : [
    {
      "text" : "Optional outcome: The user ended up successfully purchasing the product (all the way through the payment flow).",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positiveConverted"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@M@ContextSDK@E@EventOutcome@EventOutcomePositiveConverted",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "case"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "positiveConverted"
      }
    ],
    "modules" : [
      {
        "name" : "ContextSDK"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "EventOutcomePositiveConverted"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Case",
    "symbolKind" : "case",
    "title" : "EventOutcome.positiveConverted"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "case"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "positiveConverted"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/contextsdk\/eventoutcome\/positiveconverted"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/contextsdk\/eventoutcome\/positiveconverted"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "ContextSDK",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome": {
  "abstract" : [
    {
      "text" : "Represents possible outcomes of contexts logged in ContextSDK.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "EventOutcome"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "EventOutcome"
    }
  ],
  "role" : "symbol",
  "title" : "EventOutcome",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/positiveConverted": {
  "abstract" : [
    {
      "text" : "Optional outcome: The user ended up successfully purchasing the product (all the way through the payment flow).",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "positiveConverted"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positiveConverted",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "EventOutcomePositiveConverted"
    }
  ],
  "role" : "symbol",
  "title" : "EventOutcome.positiveConverted",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome\/positiveconverted"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Enumeration Case"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "EventOutcomePositiveConverted"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "case"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcomePositiveConverted"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "identifier",
                  "text" : "EventOutcomePositiveConverted"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/title",
        "value" : "EventOutcome"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcome"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcome"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1positiveConverted\/title",
        "value" : "EventOutcomePositiveConverted"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1positiveConverted\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcomePositiveConverted"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}