{
  "abstract" : [
    {
      "text" : "Log this when ContextSDK has recommended to skip showing an upsell prompt (",
      "type" : "text"
    },
    {
      "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context\/shouldUpsell",
      "isActive" : true,
      "type" : "reference"
    },
    {
      "text" : " is false). Logging this explicitly is not required if you use ",
      "type" : "text"
    },
    {
      "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/optimize(flowName:maxDelay:customSignals:callback:)",
      "isActive" : true,
      "type" : "reference"
    },
    {
      "text" : " as it will be handled by ContextSDK automatically.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/skipped"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@M@ContextSDK@E@EventOutcome@EventOutcomeSkipped",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "case"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "skipped"
      }
    ],
    "modules" : [
      {
        "name" : "ContextSDK"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "EventOutcomeSkipped"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Case",
    "symbolKind" : "case",
    "title" : "EventOutcome.skipped"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "case"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "skipped"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/contextsdk\/eventoutcome\/skipped"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/contextsdk\/eventoutcome\/skipped"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "ContextSDK",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Context/shouldUpsell": {
  "abstract" : [
    {
      "text" : "Whether it’s a good time to show an upsell prompt.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "shouldUpsell"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Sb",
      "text" : "Bool"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context\/shouldUpsell",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "shouldUpsell",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/context\/shouldupsell"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/optimize(flowName:maxDelay:customSignals:callback:)": {
  "abstract" : [
    {
      "text" : "Creates a new context (asynchronously).",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "optimize"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "externalParam",
      "text" : "flowName"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    },
    {
      "kind" : "text",
      "text" : ", "
    },
    {
      "kind" : "externalParam",
      "text" : "maxDelay"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Si",
      "text" : "Int"
    },
    {
      "kind" : "text",
      "text" : "?, "
    },
    {
      "kind" : "externalParam",
      "text" : "customSignals"
    },
    {
      "kind" : "text",
      "text" : ": ["
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:10ContextSDK12CustomSignalP",
      "text" : "CustomSignal"
    },
    {
      "kind" : "text",
      "text" : "], "
    },
    {
      "kind" : "externalParam",
      "text" : "callback"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:10ContextSDK0A7Closurea",
      "text" : "ContextClosure"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/optimize(flowName:maxDelay:customSignals:callback:)",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "optimize(flowName:maxDelay:customSignals:callback:)",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextmanager\/optimize(flowname:maxdelay:customsignals:callback:)"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome": {
  "abstract" : [
    {
      "text" : "Represents possible outcomes of contexts logged in ContextSDK.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "EventOutcome"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "EventOutcome"
    }
  ],
  "role" : "symbol",
  "title" : "EventOutcome",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/skipped": {
  "abstract" : [
    {
      "text" : "Log this when ContextSDK has recommended to skip showing an upsell prompt (",
      "type" : "text"
    },
    {
      "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context\/shouldUpsell",
      "isActive" : true,
      "type" : "reference"
    },
    {
      "text" : " is false). Logging this explicitly is not required if you use ",
      "type" : "text"
    },
    {
      "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/optimize(flowName:maxDelay:customSignals:callback:)",
      "isActive" : true,
      "type" : "reference"
    },
    {
      "text" : " as it will be handled by ContextSDK automatically.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "skipped"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/skipped",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "EventOutcomeSkipped"
    }
  ],
  "role" : "symbol",
  "title" : "EventOutcome.skipped",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome\/skipped"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Enumeration Case"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "EventOutcomeSkipped"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "case"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcomeSkipped"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "identifier",
                  "text" : "EventOutcomeSkipped"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/title",
        "value" : "EventOutcome"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcome"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcome"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1skipped\/title",
        "value" : "EventOutcomeSkipped"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1skipped\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcomeSkipped"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}