{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"forFirebase"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/contextsdk\/log\/forfirebase()"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/forFirebase()","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"If you don’t want to use the official ContextSDK backend, you can use this method to log the context data to your Firebase backend","type":"text"},{"text":" ","type":"text"},{"text":"This will use around ~10-15 custom parameters per event, and will log the full details of the ContextSDK outcome","type":"text"},{"type":"text","text":" "},{"text":"You can use any name for the event, as all required details are already bundled within those custom parameters","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"forFirebase","kind":"identifier"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"title":"forFirebase()","modules":[{"name":"ContextSDK"}],"externalID":"s:10ContextSDK3LogC11forFirebaseSDyS2SGyF","role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"references":{"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log":{"navigatorTitle":[{"kind":"identifier","text":"Log"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Log"}],"type":"topic","url":"\/documentation\/contextsdk\/log","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log","title":"Log","kind":"symbol","abstract":[]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log/forFirebase()":{"kind":"symbol","role":"symbol","title":"forFirebase()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forFirebase"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/forFirebase()","type":"topic","url":"\/documentation\/contextsdk\/log\/forfirebase()","abstract":[{"text":"If you don’t want to use the official ContextSDK backend, you can use this method to log the context data to your Firebase backend","type":"text"},{"type":"text","text":" "},{"text":"This will use around ~10-15 custom parameters per event, and will log the full details of the ContextSDK outcome","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You can use any name for the event, as all required details are already bundled within those custom parameters"}]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK":{"abstract":[],"type":"topic","title":"ContextSDK","url":"\/documentation\/contextsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/title","value":"Log","op":"replace"},{"value":[{"kind":"identifier","text":"Log"}],"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/navigatorTitle","value":[{"kind":"identifier","text":"Log"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}