{"abstract":[{"type":"text","text":"This method will send the current context to the official ContextSDK backend. No additional action needed after calling this method."}],"identifier":{"url":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/send()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/contextsdk\/log\/send()"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"modules":[{"name":"ContextSDK"}],"externalID":"s:10ContextSDK3LogC4sendyyF","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"send"},{"text":"()","kind":"text"}],"title":"send()","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"send","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Log"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Log","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log","role":"symbol","type":"topic","abstract":[],"title":"Log","url":"\/documentation\/contextsdk\/log"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log/send()":{"kind":"symbol","url":"\/documentation\/contextsdk\/log\/send()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"send"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/send()","title":"send()","role":"symbol","abstract":[{"type":"text","text":"This method will send the current context to the official ContextSDK backend. No additional action needed after calling this method."}]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","role":"collection","abstract":[],"title":"ContextSDK","url":"\/documentation\/contextsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/title","op":"replace","value":"Log"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/fragments","value":[{"kind":"identifier","text":"Log"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/navigatorTitle","value":[{"kind":"identifier","text":"Log"}]}]}]}