{
  "deprecationSummary" : [
    {
      "inlineContent" : [
        {
          "text" : "Use toBase64 or toData instead",
          "type" : "text"
        }
      ],
      "type" : "paragraph"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/toJSONString()"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "s:10ContextSDK3LogC12toJSONStringSSyF",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "func"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "toJSONString"
      },
      {
        "kind" : "text",
        "text" : "() -> "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:SS",
        "text" : "String"
      }
    ],
    "modules" : [
      {
        "name" : "ContextSDK"
      }
    ],
    "platforms" : [

    ],
    "role" : "symbol",
    "roleHeading" : "Instance Method",
    "symbolKind" : "method",
    "title" : "toJSONString()"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "func"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "toJSONString"
            },
            {
              "kind" : "text",
              "text" : "() -> "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:SS",
              "text" : "String"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/contextsdk\/log\/tojsonstring()"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    }
  ]
, 
"references": {
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "ContextSDK",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log": {
  "abstract" : [
    {
      "text" : "This class represents all signals, ready to be logged (sent to a backend), of a single ContextSDK event.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Log"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Log"
    }
  ],
  "role" : "symbol",
  "title" : "Log",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/log"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log/toJSONString()": {
  "abstract" : [

  ],
  "deprecated" : true,
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "toJSONString"
    },
    {
      "kind" : "text",
      "text" : "() -> "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/toJSONString()",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "toJSONString()",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/log\/tojsonstring()"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/title",
        "value" : "Log"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "Log"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "Log"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}