{
  "hierarchy" : {
    "paths" : [
      [

      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "ContextSDK",
    "modules" : [
      {
        "name" : "ContextSDK"
      }
    ],
    "role" : "collection",
    "roleHeading" : "Framework",
    "symbolKind" : "module",
    "title" : "ContextSDK"
  },
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "topicSections" : [
    {
      "anchor" : "Classes",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Configuration",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextLoader",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextPush",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/CustomSignalBool",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/CustomSignalDecimal",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/CustomSignalFloat",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/CustomSignalInt",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/CustomSignalString",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/DeviceTokenManager",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log"
      ],
      "title" : "Classes"
    },
    {
      "anchor" : "Protocols",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/CustomSignal"
      ],
      "title" : "Protocols"
    },
    {
      "anchor" : "Structures",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextModelInformation",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/RevenueEvent"
      ],
      "title" : "Structures"
    },
    {
      "anchor" : "Type-Aliases",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextClosure"
      ],
      "title" : "Type Aliases"
    },
    {
      "anchor" : "Enumerations",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/APSEnvironment",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Currency",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/PushOutcome",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/RevenueSource"
      ],
      "title" : "Enumerations"
    },
    {
      "anchor" : "Extended-Modules",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Foundation"
      ],
      "title" : "Extended Modules"
    }
  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/contextsdk"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/contextsdk"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "ContextSDK",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/APSEnvironment": {
  "abstract" : [
    {
      "text" : "Represents the Apple Push Notification Service (APNS) environment.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "APSEnvironment"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/APSEnvironment",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "APSEnvironment"
    }
  ],
  "role" : "symbol",
  "title" : "APSEnvironment",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/apsenvironment"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Configuration": {
  "abstract" : [
    {
      "text" : "A customizable object that defines the settings and preferences used to initialize ContextSDK.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Configuration"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Configuration",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Configuration"
    }
  ],
  "role" : "symbol",
  "title" : "Configuration",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/configuration"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Context": {
  "abstract" : [
    {
      "text" : "Represents a full context event in a moment in time. Use ",
      "type" : "text"
    },
    {
      "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context\/log(_:)",
      "isActive" : true,
      "type" : "reference"
    },
    {
      "text" : " to send the context to the server.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Context"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Context"
    }
  ],
  "role" : "symbol",
  "title" : "Context",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/context"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Context/log(_:)": {
  "abstract" : [
    {
      "text" : "Use this method to log an outcome and send the context event to the backend.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "log"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:@M@ContextSDK@E@EventOutcome",
      "text" : "EventOutcome"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context\/log(_:)",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "log(_:)",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/context\/log(_:)"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextClosure": {
  "abstract" : [
    {
      "text" : "A closure that receives a ",
      "type" : "text"
    },
    {
      "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context",
      "isActive" : true,
      "type" : "reference"
    },
    {
      "text" : " value.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "typealias"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ContextClosure"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextClosure",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ContextClosure"
    }
  ],
  "role" : "symbol",
  "title" : "ContextClosure",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextclosure"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextLoader": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ContextLoader"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextLoader",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ContextLoader"
    }
  ],
  "role" : "symbol",
  "title" : "ContextLoader",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextloader"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager": {
  "abstract" : [
    {
      "text" : "The main interface to be used to interact with ContextSDK.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ContextManager"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ContextManager"
    }
  ],
  "role" : "symbol",
  "title" : "ContextManager",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextmanager"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextModelInformation": {
  "abstract" : [
    {
      "text" : "A structure that contains information about the currently running model for a given flow.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "struct"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ContextModelInformation"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextModelInformation",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ContextModelInformation"
    }
  ],
  "role" : "symbol",
  "title" : "ContextModelInformation",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextmodelinformation"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextPush": {
  "abstract" : [
    {
      "text" : "Class used for managing push notification integration.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ContextPush"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextPush",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ContextPush"
    }
  ],
  "role" : "symbol",
  "title" : "ContextPush",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextpush"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextSDKVersionNumber": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "ContextSDKVersionNumber"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextSDKVersionNumber",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "ContextSDKVersionNumber",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdkversionnumber"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextSDKVersionString": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "ContextSDKVersionString"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextSDKVersionString",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "ContextSDKVersionString",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdkversionstring"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Currency": {
  "abstract" : [
    {
      "text" : "An exhaustive list for all active currency codes according to the ISO 4217 standard.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Currency"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Currency",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Currency"
    }
  ],
  "role" : "symbol",
  "title" : "Currency",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/currency"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/CustomSignal": {
  "abstract" : [
    {
      "text" : "A protocol representing a custom signal used in ContextSDK.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "protocol"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "CustomSignal"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/CustomSignal",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "CustomSignal"
    }
  ],
  "role" : "symbol",
  "title" : "CustomSignal",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/customsignal"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/CustomSignalBool": {
  "abstract" : [
    {
      "text" : "A custom signal that represents a key-value pair where the value is a boolean.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "CustomSignalBool"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/CustomSignalBool",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "CustomSignalBool"
    }
  ],
  "role" : "symbol",
  "title" : "CustomSignalBool",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/customsignalbool"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/CustomSignalDecimal": {
  "abstract" : [
    {
      "text" : "A custom signal that represents a key-value pair where the value is a decimal number.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "CustomSignalDecimal"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/CustomSignalDecimal",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "CustomSignalDecimal"
    }
  ],
  "role" : "symbol",
  "title" : "CustomSignalDecimal",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/customsignaldecimal"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/CustomSignalFloat": {
  "abstract" : [
    {
      "text" : "A custom signal that represents a key-value pair where the value is a floating-point number.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "CustomSignalFloat"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/CustomSignalFloat",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "CustomSignalFloat"
    }
  ],
  "role" : "symbol",
  "title" : "CustomSignalFloat",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/customsignalfloat"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/CustomSignalInt": {
  "abstract" : [
    {
      "text" : "A custom signal that represents a key-value pair where the value is an integer.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "CustomSignalInt"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/CustomSignalInt",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "CustomSignalInt"
    }
  ],
  "role" : "symbol",
  "title" : "CustomSignalInt",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/customsignalint"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/CustomSignalString": {
  "abstract" : [
    {
      "text" : "A custom signal that represents a key-value pair where the value is a string.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "CustomSignalString"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/CustomSignalString",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "CustomSignalString"
    }
  ],
  "role" : "symbol",
  "title" : "CustomSignalString",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/customsignalstring"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/DeviceTokenManager": {
  "abstract" : [
    {
      "text" : "Responsible for registering and sending the push token, tied together with the user ID.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "DeviceTokenManager"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/DeviceTokenManager",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "DeviceTokenManager"
    }
  ],
  "role" : "symbol",
  "title" : "DeviceTokenManager",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/devicetokenmanager"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome": {
  "abstract" : [
    {
      "text" : "Represents possible outcomes of contexts logged in ContextSDK.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "EventOutcome"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "EventOutcome"
    }
  ],
  "role" : "symbol",
  "title" : "EventOutcome",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Foundation": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Foundation",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "Foundation",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/foundation"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log": {
  "abstract" : [
    {
      "text" : "This class represents all signals, ready to be logged (sent to a backend), of a single ContextSDK event.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Log"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Log"
    }
  ],
  "role" : "symbol",
  "title" : "Log",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/log"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/PushOutcome": {
  "abstract" : [
    {
      "text" : "Represents the possible outcomes of evaluating whether to show a push notification.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "PushOutcome"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/PushOutcome",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "PushOutcome"
    }
  ],
  "role" : "symbol",
  "title" : "PushOutcome",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/pushoutcome"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/RevenueEvent": {
  "abstract" : [
    {
      "text" : "Represents an event that generated revenue, e.g. an ad impression, a donation, a tip, etc.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "struct"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "RevenueEvent"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/RevenueEvent",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "RevenueEvent"
    }
  ],
  "role" : "symbol",
  "title" : "RevenueEvent",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/revenueevent"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/RevenueSource": {
  "abstract" : [
    {
      "text" : "A source of revenue.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "RevenueSource"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/RevenueSource",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "RevenueSource"
    }
  ],
  "role" : "symbol",
  "title" : "RevenueSource",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/revenuesource"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_calibrate": {
  "abstract" : [
    {
      "text" : "Calibrates a context with the given parameters.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_calibrate"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_calibrate",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_calibrate",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_calibrate"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_context_addCustomSignalBool": {
  "abstract" : [
    {
      "text" : "Adds a custom signal with a Boolean value to a specific context.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_context_addCustomSignalBool"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_addCustomSignalBool",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_context_addCustomSignalBool",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_context_addcustomsignalbool"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_context_addCustomSignalFloat": {
  "abstract" : [
    {
      "text" : "Adds a custom signal with a floating-point value to a specific context.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_context_addCustomSignalFloat"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_addCustomSignalFloat",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_context_addCustomSignalFloat",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_context_addcustomsignalfloat"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_context_addCustomSignalInt": {
  "abstract" : [
    {
      "text" : "Adds a custom signal with an integer value to a specific context.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_context_addCustomSignalInt"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_addCustomSignalInt",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_context_addCustomSignalInt",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_context_addcustomsignalint"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_context_addCustomSignalString": {
  "abstract" : [
    {
      "text" : "Adds a custom signal with a string value to a specific context.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_context_addCustomSignalString"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_addCustomSignalString",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_context_addCustomSignalString",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_context_addcustomsignalstring"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_context_appendOutcomeMetadataBool": {
  "abstract" : [
    {
      "text" : "Appends Boolean metadata to the outcome of a specific context.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_context_appendOutcomeMetadataBool"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_appendOutcomeMetadataBool",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_context_appendOutcomeMetadataBool",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_context_appendoutcomemetadatabool"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_context_appendOutcomeMetadataFloat": {
  "abstract" : [
    {
      "text" : "Appends floating-point metadata to the outcome of a specific context.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_context_appendOutcomeMetadataFloat"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_appendOutcomeMetadataFloat",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_context_appendOutcomeMetadataFloat",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_context_appendoutcomemetadatafloat"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_context_appendOutcomeMetadataInt": {
  "abstract" : [
    {
      "text" : "Appends integer metadata to the outcome of a specific context.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_context_appendOutcomeMetadataInt"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_appendOutcomeMetadataInt",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_context_appendOutcomeMetadataInt",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_context_appendoutcomemetadataint"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_context_appendOutcomeMetadataString": {
  "abstract" : [
    {
      "text" : "Appends string metadata to the outcome of a specific context.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_context_appendOutcomeMetadataString"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_appendOutcomeMetadataString",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_context_appendOutcomeMetadataString",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_context_appendoutcomemetadatastring"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_context_log": {
  "abstract" : [
    {
      "text" : "Logs the outcome of a specific context.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_context_log"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_log",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_context_log",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_context_log"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_context_logIfNotLoggedYet": {
  "abstract" : [
    {
      "text" : "Logs the outcome of a specific context if it hasn’t been logged yet.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_context_logIfNotLoggedYet"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_logIfNotLoggedYet",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_context_logIfNotLoggedYet",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_context_logifnotloggedyet"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_context_shouldUpsell": {
  "abstract" : [
    {
      "text" : "Determines whether a specific context should trigger an upsell.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_context_shouldUpsell"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_shouldUpsell",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_context_shouldUpsell",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_context_shouldupsell"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_context_validate": {
  "abstract" : [
    {
      "text" : "Validates a specific context and returns the result as a string.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_context_validate"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_validate",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_context_validate",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_context_validate"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_fetchContext_string": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_fetchContext_string"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_fetchContext_string",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_fetchContext_string",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_fetchcontext_string"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_getNextContextID": {
  "abstract" : [
    {
      "text" : "Retrieves the next available context ID.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_getNextContextID"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_getNextContextID",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_getNextContextID",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_getnextcontextid"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_instantContext": {
  "abstract" : [
    {
      "text" : "Instantiates a context with the given parameters.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_instantContext"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_instantContext",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_instantContext",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_instantcontext"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_optimize_string": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_optimize_string"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_optimize_string",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_optimize_string",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_optimize_string"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_recentContext": {
  "abstract" : [
    {
      "text" : "Retrieves the most recent context for a given flow name.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_recentContext"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_recentContext",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_recentContext",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_recentcontext"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_releaseContext": {
  "abstract" : [
    {
      "text" : "Releases the context associated with the given ID.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_releaseContext"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_releaseContext",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_releaseContext",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_releasecontext"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_releaseCustomSignals": {
  "abstract" : [
    {
      "text" : "Releases the custom signals associated with the given context ID.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_releaseCustomSignals"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_releaseCustomSignals",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_releaseCustomSignals",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_releasecustomsignals"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_setGlobalCustomSignalBool": {
  "abstract" : [
    {
      "text" : "Sets a global custom signal with a Boolean value.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_setGlobalCustomSignalBool"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_setGlobalCustomSignalBool",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_setGlobalCustomSignalBool",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_setglobalcustomsignalbool"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_setGlobalCustomSignalFloat": {
  "abstract" : [
    {
      "text" : "Sets a global custom signal with a floating-point value.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_setGlobalCustomSignalFloat"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_setGlobalCustomSignalFloat",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_setGlobalCustomSignalFloat",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_setglobalcustomsignalfloat"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_setGlobalCustomSignalInt": {
  "abstract" : [
    {
      "text" : "Sets a global custom signal with an integer value.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_setGlobalCustomSignalInt"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_setGlobalCustomSignalInt",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_setGlobalCustomSignalInt",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_setglobalcustomsignalint"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_setGlobalCustomSignalString": {
  "abstract" : [
    {
      "text" : "Sets a global custom signal with a string value.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_setGlobalCustomSignalString"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_setGlobalCustomSignalString",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_setGlobalCustomSignalString",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_setglobalcustomsignalstring"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_setupContextManagerWithAPIBackend": {
  "abstract" : [
    {
      "text" : "Sets up the Context Manager with the provided API backend license key.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_setupContextManagerWithAPIBackend"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_setupContextManagerWithAPIBackend",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_setupContextManagerWithAPIBackend",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_setupcontextmanagerwithapibackend"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_trackEvent": {
  "abstract" : [
    {
      "text" : "Tracks a custom event with the given name and custom signals.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_trackEvent"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_trackEvent",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_trackEvent",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_trackevent"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_trackPageView": {
  "abstract" : [
    {
      "text" : "Tracks a page view with the given name and custom signals.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_trackPageView"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_trackPageView",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_trackPageView",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_trackpageview"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/contextSDK_trackUserAction": {
  "abstract" : [
    {
      "text" : "Tracks a user action with the given name and custom signals.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Note:",
      "type" : "text"
    },
    {
      "text" : " This method is intended for cross-platform interoperability only.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "contextSDK_trackUserAction"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_trackUserAction",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "contextSDK_trackUserAction",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextsdk_trackuseraction"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/topicSections",
        "value" : [
          {
            "anchor" : "Classes",
            "generated" : true,
            "identifiers" : [
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Configuration",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextLoader",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log"
            ],
            "title" : "Classes"
          },
          {
            "anchor" : "Variables",
            "generated" : true,
            "identifiers" : [
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextSDKVersionNumber",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextSDKVersionString"
            ],
            "title" : "Variables"
          },
          {
            "anchor" : "Functions",
            "generated" : true,
            "identifiers" : [
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_calibrate",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_addCustomSignalBool",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_addCustomSignalFloat",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_addCustomSignalInt",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_addCustomSignalString",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_appendOutcomeMetadataBool",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_appendOutcomeMetadataFloat",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_appendOutcomeMetadataInt",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_appendOutcomeMetadataString",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_log",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_logIfNotLoggedYet",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_shouldUpsell",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_context_validate",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_fetchContext_string",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_getNextContextID",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_instantContext",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_optimize_string",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_recentContext",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_releaseContext",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_releaseCustomSignals",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_setGlobalCustomSignalBool",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_setGlobalCustomSignalFloat",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_setGlobalCustomSignalInt",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_setGlobalCustomSignalString",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_setupContextManagerWithAPIBackend",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_trackEvent",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_trackPageView",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/contextSDK_trackUserAction"
            ],
            "title" : "Functions"
          },
          {
            "anchor" : "Enumerations",
            "generated" : true,
            "identifiers" : [
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome"
            ],
            "title" : "Enumerations"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Configuration\/title",
        "value" : "Configuration"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Configuration\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "Configuration"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Configuration\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "Configuration"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextLoader\/title",
        "value" : "ContextLoader"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextLoader\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "ContextLoader"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextLoader\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "ContextLoader"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager\/title",
        "value" : "ContextManager"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "ContextManager"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "ContextManager"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/title",
        "value" : "EventOutcome"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcome"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcome"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/title",
        "value" : "Log"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "Log"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "Log"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}