{
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/BaseLog"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@M@ContextSDK@objc(cs)BaseLog",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "class"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "BaseLog"
      }
    ],
    "modules" : [
      {
        "name" : "ContextSDK"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "BaseLog"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Class",
    "symbolKind" : "class",
    "title" : "BaseLog"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "class"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "BaseLog"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "relationshipsSections" : [
    {
      "identifiers" : [
        "doc:\/\/org.cocoapods.ContextSDK\/objc(cs)NSObject"
      ],
      "kind" : "relationships",
      "title" : "Inherits From",
      "type" : "inheritsFrom"
    },
    {
      "identifiers" : [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log"
      ],
      "kind" : "relationships",
      "title" : "Inherited By",
      "type" : "inheritedBy"
    },
    {
      "identifiers" : [
        "doc:\/\/org.cocoapods.ContextSDK\/objc(pl)NSObject",
        "doc:\/\/org.cocoapods.ContextSDK\/s7CVarArgP",
        "doc:\/\/org.cocoapods.ContextSDK\/s28CustomDebugStringConvertibleP",
        "doc:\/\/org.cocoapods.ContextSDK\/s23CustomStringConvertibleP",
        "doc:\/\/org.cocoapods.ContextSDK\/SQ",
        "doc:\/\/org.cocoapods.ContextSDK\/SH"
      ],
      "kind" : "relationships",
      "title" : "Conforms To",
      "type" : "conformsTo"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/contextsdk\/baselog"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/contextsdk\/baselog"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://org.cocoapods.ContextSDK/SH": {
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/SH",
  "title" : "Swift.Hashable",
  "type" : "unresolvable"
},
"doc://org.cocoapods.ContextSDK/SQ": {
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/SQ",
  "title" : "Swift.Equatable",
  "type" : "unresolvable"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "ContextSDK",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/BaseLog": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "BaseLog"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/BaseLog",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "BaseLog"
    }
  ],
  "role" : "symbol",
  "title" : "BaseLog",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/baselog"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/BaseLog/init": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "text",
      "text" : "- "
    },
    {
      "kind" : "identifier",
      "text" : "init"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/BaseLog\/init",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "init"
    }
  ],
  "role" : "symbol",
  "title" : "init",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/baselog\/init"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log": {
  "abstract" : [
    {
      "text" : "This class represents all signals, ready to be logged (sent to a backend), of a single ContextSDK event.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Log"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Log"
    }
  ],
  "role" : "symbol",
  "title" : "Log",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/log"
},
"doc://org.cocoapods.ContextSDK/objc(cs)NSObject": {
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/objc(cs)NSObject",
  "title" : "NSObject",
  "type" : "unresolvable"
},
"doc://org.cocoapods.ContextSDK/objc(pl)NSObject": {
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/objc(pl)NSObject",
  "title" : "ObjectiveC.NSObjectProtocol",
  "type" : "unresolvable"
},
"doc://org.cocoapods.ContextSDK/s23CustomStringConvertibleP": {
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/s23CustomStringConvertibleP",
  "title" : "Swift.CustomStringConvertible",
  "type" : "unresolvable"
},
"doc://org.cocoapods.ContextSDK/s28CustomDebugStringConvertibleP": {
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/s28CustomDebugStringConvertibleP",
  "title" : "Swift.CustomDebugStringConvertible",
  "type" : "unresolvable"
},
"doc://org.cocoapods.ContextSDK/s7CVarArgP": {
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/s7CVarArgP",
  "title" : "Swift.CVarArg",
  "type" : "unresolvable"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Class"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "BaseLog"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "class"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "BaseLog"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "BaseLog"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : [
          {
            "anchor" : "Instance-Methods",
            "generated" : true,
            "identifiers" : [
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/BaseLog\/init"
            ],
            "title" : "Instance Methods"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/relationshipsSections",
        "value" : [
          {
            "identifiers" : [
              "doc:\/\/org.cocoapods.ContextSDK\/objc(cs)NSObject"
            ],
            "kind" : "relationships",
            "title" : "Inherits From",
            "type" : "inheritsFrom"
          },
          {
            "identifiers" : [
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log"
            ],
            "kind" : "relationships",
            "title" : "Inherited By",
            "type" : "inheritedBy"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "@interface"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "identifier",
                  "text" : "BaseLog"
                },
                {
                  "kind" : "text",
                  "text" : " : "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:objc(cs)NSObject",
                  "text" : "NSObject"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1BaseLog\/title",
        "value" : "BaseLog"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1BaseLog\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "BaseLog"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1BaseLog\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "BaseLog"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/title",
        "value" : "Log"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "Log"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "Log"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}