{"metadata":{"modules":[{"name":"ContextSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ContextManager"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@ContextSDK@objc(cs)ContextManager","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContextManager"}],"title":"ContextManager"},"identifier":{"url":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/contextsdk\/contextmanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/contextsdk\/contextmanager"]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/applicationDidFinishLaunchingWithOptions(_:licenseKey:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/applicationDidFinishLaunchingWithOptions(_:licenseKey:configuration:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/calibrate(_:maxDelay:customSignals:callback:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/cancelContextCallback(flowName:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/contextPush()","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/currentAppliedCustomModelVersion()","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/fetchContext(flowName:duration:customSignals:callback:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/getCustomModel(for:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/instantContext(flowName:duration:customSignals:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/optimize(flowName:maxDelay:customSignals:callback:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/recentContext(flowName:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/sdkVersion()","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setControlMode(enabled:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setGlobalCustomSignal(id:decimalValue:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setGlobalCustomSignal(id:value:)-6cp7d","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setGlobalCustomSignal(id:value:)-6pc7c","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setGlobalCustomSignal(id:value:)-8onnm","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setGlobalCustomSignal(id:value:)-8xovt","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setLogSender(closure:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setup(_:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setup(_:configuration:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setup(licenseKey:defaultLogSender:configuration:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/trackEvent(_:customSignals:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/trackPageView(_:customSignals:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/trackUserAction(_:customSignals:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContextManager"}]}],"kind":"declarations"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ContextSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ContextSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ContextSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ContextSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ContextSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ContextSDK\/SQ","doc:\/\/org.cocoapods.ContextSDK\/SH"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/currentAppliedCustomModelVersion()":{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/currentAppliedCustomModelVersion()","type":"topic","title":"currentAppliedCustomModelVersion()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"currentAppliedCustomModelVersion","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/contextsdk\/contextmanager\/currentappliedcustommodelversion()","role":"symbol","kind":"symbol","abstract":[]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/trackUserAction(_:customSignals:)":{"url":"\/documentation\/contextsdk\/contextmanager\/trackuseraction(_:customsignals:)","role":"symbol","type":"topic","kind":"symbol","title":"trackUserAction(_:customSignals:)","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/trackUserAction(_:customSignals:)","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"trackUserAction","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"customSignals","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10ContextSDK12CustomSignalP","text":"CustomSignal","kind":"typeIdentifier"},{"kind":"text","text":"])"}]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/trackEvent(_:customSignals:)":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackEvent"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"customSignals"},{"kind":"text","text":": ["},{"text":"CustomSignal","preciseIdentifier":"s:10ContextSDK12CustomSignalP","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/trackEvent(_:customSignals:)","title":"trackEvent(_:customSignals:)","url":"\/documentation\/contextsdk\/contextmanager\/trackevent(_:customsignals:)","abstract":[],"kind":"symbol","type":"topic"},"doc://org.cocoapods.ContextSDK/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/setLogSender(closure:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setLogSender","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"closure"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ContextSDK@objc(cs)Log","text":"Log","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":"))","kind":"text"}],"role":"symbol","deprecated":true,"kind":"symbol","title":"setLogSender(closure:)","type":"topic","url":"\/documentation\/contextsdk\/contextmanager\/setlogsender(closure:)","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setLogSender(closure:)"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/applicationDidFinishLaunchingWithOptions(_:licenseKey:configuration:)":{"navigatorTitle":[{"text":"applicationDidFinishLaunchingWithOptions:licenseKey:configuration:","kind":"identifier"}],"url":"\/documentation\/contextsdk\/contextmanager\/applicationdidfinishlaunchingwithoptions(_:licensekey:configuration:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/applicationDidFinishLaunchingWithOptions(_:licenseKey:configuration:)","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationDidFinishLaunchingWithOptions"},{"text":"([","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"text":"LaunchOptionsKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"text":"licenseKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ContextSDK@objc(cs)Configuration"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"applicationDidFinishLaunchingWithOptions(_:licenseKey:configuration:)"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/setup(licenseKey:defaultLogSender:configuration:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"text":"licenseKey","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"defaultLogSender","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@ContextSDK@objc(cs)Log","text":"Log","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ContextSDK@objc(cs)Configuration","text":"Configuration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"deprecated":true,"title":"setup(licenseKey:defaultLogSender:configuration:)","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setup(licenseKey:defaultLogSender:configuration:)","kind":"symbol","type":"topic","url":"\/documentation\/contextsdk\/contextmanager\/setup(licensekey:defaultlogsender:configuration:)","navigatorTitle":[{"kind":"identifier","text":"setupWithLicenseKey:defaultLogSender:configuration:"}],"abstract":[],"role":"symbol"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/fetchContext(flowName:duration:customSignals:callback:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/fetchContext(flowName:duration:customSignals:callback:)","abstract":[],"url":"\/documentation\/contextsdk\/contextmanager\/fetchcontext(flowname:duration:customsignals:callback:)","title":"fetchContext(flowName:duration:customSignals:callback:)","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchContext","kind":"identifier"},{"kind":"text","text":"("},{"text":"flowName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"customSignals","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"CustomSignal","kind":"typeIdentifier","preciseIdentifier":"s:10ContextSDK12CustomSignalP"},{"kind":"text","text":"], "},{"text":"callback","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Context","preciseIdentifier":"s:10ContextSDK0A0C","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":"))"}]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/calibrate(_:maxDelay:customSignals:callback:)":{"title":"calibrate(_:maxDelay:customSignals:callback:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"calibrate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"maxDelay","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"customSignals"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10ContextSDK12CustomSignalP","text":"CustomSignal","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Context","preciseIdentifier":"s:10ContextSDK0A0C","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":"))"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/calibrate(_:maxDelay:customSignals:callback:)","url":"\/documentation\/contextsdk\/contextmanager\/calibrate(_:maxdelay:customsignals:callback:)","kind":"symbol","abstract":[]},"doc://org.cocoapods.ContextSDK/SH":{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/setGlobalCustomSignal(id:value:)-6cp7d":{"type":"topic","title":"setGlobalCustomSignal(id:value:)","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setGlobalCustomSignal(id:value:)-6cp7d","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setGlobalCustomSignal","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"url":"\/documentation\/contextsdk\/contextmanager\/setglobalcustomsignal(id:value:)-6cp7d","role":"symbol"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/setControlMode(enabled:)":{"title":"setControlMode(enabled:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setControlMode"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"enabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setControlMode(enabled:)","abstract":[],"url":"\/documentation\/contextsdk\/contextmanager\/setcontrolmode(enabled:)","kind":"symbol","type":"topic"},"doc://org.cocoapods.ContextSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ContextSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/setGlobalCustomSignal(id:value:)-8xovt":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setGlobalCustomSignal(id:value:)-8xovt","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setGlobalCustomSignal","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/contextsdk\/contextmanager\/setglobalcustomsignal(id:value:)-8xovt","kind":"symbol","title":"setGlobalCustomSignal(id:value:)"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/sdkVersion()":{"url":"\/documentation\/contextsdk\/contextmanager\/sdkversion()","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/sdkVersion()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sdkVersion","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"sdkVersion","kind":"identifier"}],"title":"sdkVersion()"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/setGlobalCustomSignal(id:value:)-6pc7c":{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setGlobalCustomSignal(id:value:)-6pc7c","title":"setGlobalCustomSignal(id:value:)","type":"topic","url":"\/documentation\/contextsdk\/contextmanager\/setglobalcustomsignal(id:value:)-6pc7c","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setGlobalCustomSignal","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/recentContext(flowName:)":{"url":"\/documentation\/contextsdk\/contextmanager\/recentcontext(flowname:)","abstract":[{"text":"Fetch the most recently generated Context for a given flowName","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/recentContext(flowName:)","title":"recentContext(flowName:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recentContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"flowName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10ContextSDK0A0C","kind":"typeIdentifier","text":"Context"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ContextManager","kind":"identifier"}],"navigatorTitle":[{"text":"ContextManager","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/contextsdk\/contextmanager","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager","title":"ContextManager"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/applicationDidFinishLaunchingWithOptions(_:licenseKey:)":{"url":"\/documentation\/contextsdk\/contextmanager\/applicationdidfinishlaunchingwithoptions(_:licensekey:)","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"applicationDidFinishLaunchingWithOptions:licenseKey:"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/applicationDidFinishLaunchingWithOptions(_:licenseKey:)","title":"applicationDidFinishLaunchingWithOptions(_:licenseKey:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationDidFinishLaunchingWithOptions","kind":"identifier"},{"kind":"text","text":"(["},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"LaunchOptionsKey","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"text":"licenseKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/setup(_:configuration:)":{"url":"\/documentation\/contextsdk\/contextmanager\/setup(_:configuration:)","type":"topic","role":"symbol","title":"setup(_:configuration:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setup","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ContextSDK@objc(cs)Configuration","text":"Configuration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[],"deprecated":true,"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setup(_:configuration:)","navigatorTitle":[{"text":"setup:configuration:","kind":"identifier"}]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/trackPageView(_:customSignals:)":{"type":"topic","url":"\/documentation\/contextsdk\/contextmanager\/trackpageview(_:customsignals:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPageView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customSignals"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:10ContextSDK12CustomSignalP","text":"CustomSignal"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/trackPageView(_:customSignals:)","title":"trackPageView(_:customSignals:)","abstract":[],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/cancelContextCallback(flowName:)":{"url":"\/documentation\/contextsdk\/contextmanager\/cancelcontextcallback(flowname:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/cancelContextCallback(flowName:)","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelContextCallback","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"flowName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"cancelContextCallback(flowName:)"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","role":"collection","type":"topic","url":"\/documentation\/contextsdk","kind":"symbol","title":"ContextSDK"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/setGlobalCustomSignal(id:value:)-8onnm":{"url":"\/documentation\/contextsdk\/contextmanager\/setglobalcustomsignal(id:value:)-8onnm","role":"symbol","abstract":[],"title":"setGlobalCustomSignal(id:value:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setGlobalCustomSignal","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setGlobalCustomSignal(id:value:)-8onnm","type":"topic"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/instantContext(flowName:duration:customSignals:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"instantContext"},{"text":"(","kind":"text"},{"text":"flowName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"customSignals","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CustomSignal","preciseIdentifier":"s:10ContextSDK12CustomSignalP"},{"kind":"text","text":"]) -> "},{"text":"Context","kind":"typeIdentifier","preciseIdentifier":"s:10ContextSDK0A0C"}],"url":"\/documentation\/contextsdk\/contextmanager\/instantcontext(flowname:duration:customsignals:)","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/instantContext(flowName:duration:customSignals:)","abstract":[],"title":"instantContext(flowName:duration:customSignals:)","kind":"symbol"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/setGlobalCustomSignal(id:decimalValue:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setGlobalCustomSignal","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"decimalValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Decimal","kind":"typeIdentifier","preciseIdentifier":"c:@SA@NSDecimal"},{"text":")","kind":"text"}],"title":"setGlobalCustomSignal(id:decimalValue:)","abstract":[],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/contextsdk\/contextmanager\/setglobalcustomsignal(id:decimalvalue:)","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setGlobalCustomSignal(id:decimalValue:)"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/setup(_:)":{"navigatorTitle":[{"kind":"identifier","text":"setup:"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setup(_:)","title":"setup(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/contextsdk\/contextmanager\/setup(_:)","deprecated":true},"doc://org.cocoapods.ContextSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ContextSDK\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.ContextSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ContextSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/optimize(flowName:maxDelay:customSignals:callback:)":{"url":"\/documentation\/contextsdk\/contextmanager\/optimize(flowname:maxdelay:customsignals:callback:)","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/optimize(flowName:maxDelay:customSignals:callback:)","abstract":[],"role":"symbol","title":"optimize(flowName:maxDelay:customSignals:callback:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"optimize","kind":"identifier"},{"kind":"text","text":"("},{"text":"flowName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"maxDelay","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customSignals"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CustomSignal","preciseIdentifier":"s:10ContextSDK12CustomSignalP"},{"text":"], ","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"Context","kind":"typeIdentifier","preciseIdentifier":"s:10ContextSDK0A0C"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":"))","kind":"text"}]},"doc://org.cocoapods.ContextSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ContextSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/contextPush()":{"kind":"symbol","title":"contextPush()","type":"topic","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/contextPush()","abstract":[],"url":"\/documentation\/contextsdk\/contextmanager\/contextpush()","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"contextPush","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:10ContextSDK0A4PushC","text":"ContextPush","kind":"typeIdentifier"}]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/getCustomModel(for:)":{"title":"getCustomModel(for:)","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/getCustomModel(for:)","type":"topic","role":"symbol","abstract":[{"text":"Returns the current context model information for the specified flow name.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCustomModel"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ContextModelInformation","preciseIdentifier":"s:10ContextSDK0A16ModelInformationV"},{"kind":"text","text":"?"}],"url":"\/documentation\/contextsdk\/contextmanager\/getcustommodel(for:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ContextManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"ContextManager"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ContextManager","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/applicationDidFinishLaunchingWithOptions(_:licenseKey:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/applicationDidFinishLaunchingWithOptions(_:licenseKey:configuration:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/sdkVersion()","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setup(_:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setup(_:configuration:)","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/setup(licenseKey:defaultLogSender:configuration:)"],"anchor":"Type-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ContextSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContextManager"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1applicationDidFinishLaunchingWithOptions(_:licenseKey:configuration:)\/title","value":"applicationDidFinishLaunchingWithOptions:licenseKey:configuration:"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1applicationDidFinishLaunchingWithOptions(_:licenseKey:configuration:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"applicationDidFinishLaunchingWithOptions:licenseKey:configuration:","kind":"identifier"}]},{"op":"replace","value":"setupWithLicenseKey:defaultLogSender:configuration:","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1setup(licenseKey:defaultLogSender:configuration:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1setup(licenseKey:defaultLogSender:configuration:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setupWithLicenseKey:defaultLogSender:configuration:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1sdkVersion()\/title","value":"sdkVersion"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1sdkVersion()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"sdkVersion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager\/title","value":"ContextManager"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager\/fragments","value":[{"text":"ContextManager","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ContextManager"}],"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager\/navigatorTitle"},{"value":"applicationDidFinishLaunchingWithOptions:licenseKey:","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1applicationDidFinishLaunchingWithOptions(_:licenseKey:)\/title","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"applicationDidFinishLaunchingWithOptions:licenseKey:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1applicationDidFinishLaunchingWithOptions(_:licenseKey:)\/fragments"},{"value":"setup:configuration:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1setup(_:configuration:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1setup(_:configuration:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setup:configuration:","kind":"identifier"}],"op":"replace"},{"value":"setup:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1setup(_:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"setup:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextManager~1setup(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}