{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK"]]},"variants":[{"paths":["\/documentation\/contextsdk\/contextloader"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/contextsdk\/contextloader"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContextLoader","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextLoader","interfaceLanguage":"swift"},"metadata":{"title":"ContextLoader","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"ContextLoader"}],"role":"symbol","modules":[{"name":"ContextSDK"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContextLoader","kind":"identifier"}],"externalID":"c:objc(cs)ContextLoader"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ContextSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/org.cocoapods.ContextSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ContextSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ContextSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ContextSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ContextSDK\/SQ","doc:\/\/org.cocoapods.ContextSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"kind":"symbol","references":{"doc://org.cocoapods.ContextSDK/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.ContextSDK/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.ContextSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.ContextSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","role":"collection","abstract":[],"title":"ContextSDK","url":"\/documentation\/contextsdk","type":"topic"},"doc://org.cocoapods.ContextSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.ContextSDK/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.ContextSDK/SH":{"identifier":"doc:\/\/org.cocoapods.ContextSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextLoader":{"kind":"symbol","abstract":[],"title":"ContextLoader","url":"\/documentation\/contextsdk\/contextloader","type":"topic","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextLoader","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ContextLoader","kind":"identifier"}],"navigatorTitle":[{"text":"ContextLoader","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"ContextLoader"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ContextLoader"}]},{"op":"replace","value":[{"text":"ContextLoader","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ContextSDK\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContextLoader"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"ContextLoader","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextLoader\/title"},{"op":"replace","value":[{"text":"ContextLoader","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextLoader\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1ContextLoader\/navigatorTitle","value":[{"text":"ContextLoader","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}