{
  "abstract" : [
    {
      "text" : "Represents possible outcomes of contexts logged in ContextSDK.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@M@ContextSDK@E@EventOutcome",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "enum"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "EventOutcome"
      }
    ],
    "modules" : [
      {
        "name" : "ContextSDK"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "EventOutcome"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Enumeration",
    "symbolKind" : "enum",
    "title" : "EventOutcome"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "attribute",
              "text" : "@objc"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "keyword",
              "text" : "enum"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "EventOutcome"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "content" : [
        {
          "anchor" : "overview",
          "level" : 2,
          "text" : "Overview",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "Use this enum to categorize the outcomes of user interactions with features like ads, banners, and upsell prompts.",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "The values provide varying levels of granularity for both positive and negative signals. If a given flow only has 2 possible outcomes, we recommend using simply ",
              "type" : "text"
            },
            {
              "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positive",
              "isActive" : true,
              "type" : "reference"
            },
            {
              "text" : " and ",
              "type" : "text"
            },
            {
              "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negative",
              "isActive" : true,
              "type" : "reference"
            },
            {
              "text" : ".",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "relationshipsSections" : [
    {
      "identifiers" : [
        "doc:\/\/org.cocoapods.ContextSDK\/s23CustomStringConvertibleP",
        "doc:\/\/org.cocoapods.ContextSDK\/SQ",
        "doc:\/\/org.cocoapods.ContextSDK\/SH",
        "doc:\/\/org.cocoapods.ContextSDK\/SY"
      ],
      "kind" : "relationships",
      "title" : "Conforms To",
      "type" : "conformsTo"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "topicSections" : [
    {
      "anchor" : "Enumeration-Cases",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negative",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negativeDismissed",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negativeNotInteracted",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positive",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positiveAdTapped",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positiveConverted",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positiveInteracted",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/skipped"
      ],
      "title" : "Enumeration Cases"
    },
    {
      "anchor" : "Initializers",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/init(rawValue:)"
      ],
      "title" : "Initializers"
    },
    {
      "anchor" : "Instance-Properties",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/description"
      ],
      "title" : "Instance Properties"
    },
    {
      "anchor" : "Default-Implementations",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/Equatable-Implementations",
        "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/RawRepresentable-Implementations"
      ],
      "title" : "Default Implementations"
    }
  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/contextsdk\/eventoutcome"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/contextsdk\/eventoutcome"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://org.cocoapods.ContextSDK/SH": {
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/SH",
  "title" : "Swift.Hashable",
  "type" : "unresolvable"
},
"doc://org.cocoapods.ContextSDK/SQ": {
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/SQ",
  "title" : "Swift.Equatable",
  "type" : "unresolvable"
},
"doc://org.cocoapods.ContextSDK/SY": {
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/SY",
  "title" : "Swift.RawRepresentable",
  "type" : "unresolvable"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "ContextSDK",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Context/logIfNotLoggedYet(_:)": {
  "abstract" : [
    {
      "text" : "Use this function to log an outcome only if this particular context object hasn’t been logged yet.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "logIfNotLoggedYet"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:@M@ContextSDK@E@EventOutcome",
      "text" : "EventOutcome"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context\/logIfNotLoggedYet(_:)",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "logIfNotLoggedYet(_:)",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/context\/logifnotloggedyet(_:)"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Context/shouldUpsell": {
  "abstract" : [
    {
      "text" : "Whether it’s a good time to show an upsell prompt.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "shouldUpsell"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Sb",
      "text" : "Bool"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context\/shouldUpsell",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "shouldUpsell",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/context\/shouldupsell"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/ContextManager/optimize(flowName:maxDelay:customSignals:callback:)": {
  "abstract" : [
    {
      "text" : "Creates a new context (asynchronously).",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "optimize"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "externalParam",
      "text" : "flowName"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    },
    {
      "kind" : "text",
      "text" : ", "
    },
    {
      "kind" : "externalParam",
      "text" : "maxDelay"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Si",
      "text" : "Int"
    },
    {
      "kind" : "text",
      "text" : "?, "
    },
    {
      "kind" : "externalParam",
      "text" : "customSignals"
    },
    {
      "kind" : "text",
      "text" : ": ["
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:10ContextSDK12CustomSignalP",
      "text" : "CustomSignal"
    },
    {
      "kind" : "text",
      "text" : "], "
    },
    {
      "kind" : "externalParam",
      "text" : "callback"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:10ContextSDK0A7Closurea",
      "text" : "ContextClosure"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/optimize(flowName:maxDelay:customSignals:callback:)",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "optimize(flowName:maxDelay:customSignals:callback:)",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/contextmanager\/optimize(flowname:maxdelay:customsignals:callback:)"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome": {
  "abstract" : [
    {
      "text" : "Represents possible outcomes of contexts logged in ContextSDK.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "EventOutcome"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "EventOutcome"
    }
  ],
  "role" : "symbol",
  "title" : "EventOutcome",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/Equatable-Implementations": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/Equatable-Implementations",
  "kind" : "article",
  "role" : "collectionGroup",
  "title" : "Equatable Implementations",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome\/equatable-implementations"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/RawRepresentable-Implementations": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/RawRepresentable-Implementations",
  "kind" : "article",
  "role" : "collectionGroup",
  "title" : "RawRepresentable Implementations",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome\/rawrepresentable-implementations"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/description": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "description"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/description",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "description",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome\/description"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/init(rawValue:)": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "init"
    },
    {
      "kind" : "text",
      "text" : "?("
    },
    {
      "kind" : "externalParam",
      "text" : "rawValue"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Si",
      "text" : "Int"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/init(rawValue:)",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "init(rawValue:)",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome\/init(rawvalue:)"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/negative": {
  "abstract" : [
    {
      "text" : "A generic, negative signal. Use this for the basic ContextSDK integration, on a user e.g. declining or dismissing an upsell prompt.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "negative"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negative",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "EventOutcomeNegative"
    }
  ],
  "role" : "symbol",
  "title" : "EventOutcome.negative",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome\/negative"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/negativeDismissed": {
  "abstract" : [
    {
      "text" : "Optional outcome: The user has actively dismissed the banner (e.g. using a close button).",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "negativeDismissed"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negativeDismissed",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "EventOutcomeNegativeDismissed"
    }
  ],
  "role" : "symbol",
  "title" : "EventOutcome.negativeDismissed",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome\/negativedismissed"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/negativeNotInteracted": {
  "abstract" : [
    {
      "text" : "Optional outcome: Use this as a negative signal of a user not interacting with e.g. a banner. Depending on your app, we may recommend to log this when the app is put into the background, and hasn’t interacted with a banner in any way. This can be done using the ",
      "type" : "text"
    },
    {
      "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context\/logIfNotLoggedYet(_:)",
      "isActive" : true,
      "type" : "reference"
    },
    {
      "text" : " method.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "negativeNotInteracted"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negativeNotInteracted",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "EventOutcomeNegativeNotInteracted"
    }
  ],
  "role" : "symbol",
  "title" : "EventOutcome.negativeNotInteracted",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome\/negativenotinteracted"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/positive": {
  "abstract" : [
    {
      "text" : "The default signal. A generic, positive signal. Use this for the basic ContextSDK integration, e.g. when showing an upsell prompt.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "positive"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positive",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "EventOutcomePositive"
    }
  ],
  "role" : "symbol",
  "title" : "EventOutcome.positive",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome\/positive"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/positiveAdTapped": {
  "abstract" : [
    {
      "text" : "Optional outcome: The user has tapped on the ad, and followed any external link provided.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "positiveAdTapped"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positiveAdTapped",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "EventOutcomePositiveAdTapped"
    }
  ],
  "role" : "symbol",
  "title" : "EventOutcome.positiveAdTapped",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome\/positiveadtapped"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/positiveConverted": {
  "abstract" : [
    {
      "text" : "Optional outcome: The user ended up successfully purchasing the product (all the way through the payment flow).",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "positiveConverted"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positiveConverted",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "EventOutcomePositiveConverted"
    }
  ],
  "role" : "symbol",
  "title" : "EventOutcome.positiveConverted",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome\/positiveconverted"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/positiveInteracted": {
  "abstract" : [
    {
      "text" : "Optional outcome: The user has tapped on the banner, and started the purchase flow, or read more about the offer.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "positiveInteracted"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positiveInteracted",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "EventOutcomePositiveInteracted"
    }
  ],
  "role" : "symbol",
  "title" : "EventOutcome.positiveInteracted",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome\/positiveinteracted"
},
"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/EventOutcome/skipped": {
  "abstract" : [
    {
      "text" : "Log this when ContextSDK has recommended to skip showing an upsell prompt (",
      "type" : "text"
    },
    {
      "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Context\/shouldUpsell",
      "isActive" : true,
      "type" : "reference"
    },
    {
      "text" : " is false). Logging this explicitly is not required if you use ",
      "type" : "text"
    },
    {
      "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/ContextManager\/optimize(flowName:maxDelay:customSignals:callback:)",
      "isActive" : true,
      "type" : "reference"
    },
    {
      "text" : " as it will be handled by ContextSDK automatically.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "skipped"
    }
  ],
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/skipped",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "EventOutcomeSkipped"
    }
  ],
  "role" : "symbol",
  "title" : "EventOutcome.skipped",
  "type" : "topic",
  "url" : "\/documentation\/contextsdk\/eventoutcome\/skipped"
},
"doc://org.cocoapods.ContextSDK/s23CustomStringConvertibleP": {
  "identifier" : "doc:\/\/org.cocoapods.ContextSDK\/s23CustomStringConvertibleP",
  "title" : "Swift.CustomStringConvertible",
  "type" : "unresolvable"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Enumeration"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "EventOutcome"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "enum"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcome"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcome"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/topicSections",
        "value" : [
          {
            "anchor" : "Enumeration-Cases",
            "generated" : true,
            "identifiers" : [
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negative",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negativeDismissed",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/negativeNotInteracted",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positive",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positiveAdTapped",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positiveConverted",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/positiveInteracted",
              "doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/EventOutcome\/skipped"
            ],
            "title" : "Enumeration Cases"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "enum"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "identifier",
                  "text" : "EventOutcome"
                },
                {
                  "kind" : "text",
                  "text" : ": "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@T@NSInteger",
                  "text" : "NSInteger"
                },
                {
                  "kind" : "text",
                  "text" : ";"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/title",
        "value" : "EventOutcome"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcome"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcome"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1negative\/title",
        "value" : "EventOutcomeNegative"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1negative\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcomeNegative"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1negativeDismissed\/title",
        "value" : "EventOutcomeNegativeDismissed"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1negativeDismissed\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcomeNegativeDismissed"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1negativeNotInteracted\/title",
        "value" : "EventOutcomeNegativeNotInteracted"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1negativeNotInteracted\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcomeNegativeNotInteracted"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1positive\/title",
        "value" : "EventOutcomePositive"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1positive\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcomePositive"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1positiveAdTapped\/title",
        "value" : "EventOutcomePositiveAdTapped"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1positiveAdTapped\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcomePositiveAdTapped"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1positiveConverted\/title",
        "value" : "EventOutcomePositiveConverted"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1positiveConverted\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcomePositiveConverted"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1positiveInteracted\/title",
        "value" : "EventOutcomePositiveInteracted"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1positiveInteracted\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcomePositiveInteracted"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1skipped\/title",
        "value" : "EventOutcomeSkipped"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1EventOutcome~1skipped\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "EventOutcomeSkipped"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}