{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/dictionary()","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/dictionaryWithStaticColumns()","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/forFirebase()","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/send()","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/toBase64()","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/toData()","doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/toJSONString()"],"title":"Instance Methods","generated":true}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ContextSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ContextSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ContextSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ContextSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ContextSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ContextSDK\/SQ","doc:\/\/org.cocoapods.ContextSDK\/SH"],"title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Log"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"This class represents all signals, ready to be logged (sent to a backend), of a single ContextSDK event"}],"type":"paragraph"}]}]}]}],"variants":[{"paths":["\/documentation\/contextsdk\/log"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/contextsdk\/log"]}],"metadata":{"role":"symbol","roleHeading":"Class","symbolKind":"class","modules":[{"name":"ContextSDK"}],"navigatorTitle":[{"kind":"identifier","text":"Log"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Log"}],"externalID":"c:@M@ContextSDK@objc(cs)Log","title":"Log"},"identifier":{"url":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ContextSDK/documentation/ContextSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK","role":"collection","abstract":[],"title":"ContextSDK","url":"\/documentation\/contextsdk","type":"topic"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log/dictionaryWithStaticColumns()":{"title":"dictionaryWithStaticColumns()","role":"symbol","url":"\/documentation\/contextsdk\/log\/dictionarywithstaticcolumns()","type":"topic","abstract":[{"text":"If you don’t want to use the official ContextSDK backend, you can use this method to create a dictionary with a fixed number of columns","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This method can be used when you need the exact columns your backend or database requires the exact columns"},{"type":"text","text":" "},{"type":"text","text":"This becomes particularly relevant when you provide custom signals, and your backend doesn’t have flexible columns"},{"type":"text","text":" "},{"text":"This method will append a ","type":"text"},{"code":"ctx_custom_signals","type":"codeVoice"},{"type":"text","text":" column, that contains all custom signals."}],"kind":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/dictionaryWithStaticColumns()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"dictionaryWithStaticColumns","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log/toData()":{"kind":"symbol","url":"\/documentation\/contextsdk\/log\/todata()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toData"},{"kind":"text","text":"() -> "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/toData()","title":"toData()","role":"symbol","abstract":[]},"doc://org.cocoapods.ContextSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ContextSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log/toJSONString()":{"kind":"symbol","url":"\/documentation\/contextsdk\/log\/tojsonstring()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJSONString"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/toJSONString()","title":"toJSONString()","deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"If you don’t want to use the official ContextSDK backend, you can use this method to create a JSON string"},{"type":"text","text":" "},{"type":"text","text":"This single JSON String can be stored in your own database. Use this method if your backend doesn’t support"},{"type":"text","text":" "},{"type":"text","text":"flexible columns, or a high number of columns"}]},"doc://org.cocoapods.ContextSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ContextSDK\/objc(pl)NSObject"},"doc://org.cocoapods.ContextSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ContextSDK\/SQ"},"doc://org.cocoapods.ContextSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ContextSDK\/SH"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log/send()":{"kind":"symbol","url":"\/documentation\/contextsdk\/log\/send()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"send"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/send()","title":"send()","role":"symbol","abstract":[{"type":"text","text":"This method will send the current context to the official ContextSDK backend. No additional action needed after calling this method."}]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log/toBase64()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toBase64"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/toBase64()","role":"symbol","type":"topic","abstract":[],"title":"toBase64()","url":"\/documentation\/contextsdk\/log\/tobase64()"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log/forFirebase()":{"kind":"symbol","url":"\/documentation\/contextsdk\/log\/forfirebase()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"forFirebase"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/forFirebase()","title":"forFirebase()","role":"symbol","abstract":[{"type":"text","text":"If you don’t want to use the official ContextSDK backend, you can use this method to log the context data to your Firebase backend"},{"type":"text","text":" "},{"type":"text","text":"This will use around ~10-15 custom parameters per event, and will log the full details of the ContextSDK outcome"},{"type":"text","text":" "},{"type":"text","text":"You can use any name for the event, as all required details are already bundled within those custom parameters"}]},"doc://org.cocoapods.ContextSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ContextSDK\/objc(cs)NSObject"},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log/dictionary()":{"kind":"symbol","url":"\/documentation\/contextsdk\/log\/dictionary()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dictionary"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log\/dictionary()","title":"dictionary()","role":"symbol","abstract":[{"type":"text","text":"If you don’t want to use the official ContextSDK backend, you can use this method to create a dictionary"},{"type":"text","text":" "},{"type":"text","text":"that you can send to your own analytics backend. Note that this method may return a different number of columns"},{"type":"text","text":" "},{"type":"text","text":"depending on the number of custom signals you have set, as well as additional signals being added to the ContextSDK with each update"},{"type":"text","text":" "},{"type":"text","text":"Columns are mostly static though and new ones will only ever be appended in the format “ctx_{ID}”"}]},"doc://org.cocoapods.ContextSDK/documentation/ContextSDK/Log":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Log"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Log","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ContextSDK\/documentation\/ContextSDK\/Log","role":"symbol","type":"topic","abstract":[],"title":"Log","url":"\/documentation\/contextsdk\/log"},"doc://org.cocoapods.ContextSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ContextSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.ContextSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ContextSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"Log"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"Log","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"Log","kind":"identifier"}]},{"value":null,"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ContextSDK\/objc(cs)NSObject"]}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"Log","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"Log","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/fragments","op":"replace","value":[{"kind":"identifier","text":"Log"}]},{"op":"replace","value":[{"kind":"identifier","text":"Log"}],"path":"\/references\/doc:~1~1org.cocoapods.ContextSDK~1documentation~1ContextSDK~1Log\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}